[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../shared" }
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "line_series", "histogram", "ab_glyph"] }
plotters-bitmap = "0.3"
minijinja = "2"

[[bin]]
name = "mv_compare"
path = "mv_compare.rs"

[[bin]]
name = "vtune_hotspots_plot"
path = "vtune_hotspots_plot.rs"
