use std::ffi::CStr;
use std::fs::File;
use std::io::BufWriter;
use std::ffi::CString;
use std::ptr;

use ffmpeg_sys_next::{self as ff, AVMotionVector};
use mv_types::motion_vector::{MotionVector, MotionVectorCsvWriter, MvCompactCsvWriter};

/// Mirror of the C struct added by the custom FFmpeg patch.
/// Not generated by bindgen because ffmpeg-sys-next's allowlist only covers
/// the upstream AVMotionVector; layout must stay in sync with motion_vector.h.
#[cfg(feature = "custom_ffmpeg")]
#[repr(C)]
pub struct AVMotionVectorCompact {
    pub source: i32,
    pub src_x: i16,
    pub src_y: i16,
    pub dst_x: i16,
    pub dst_y: i16,
}
#[cfg(feature = "custom_ffmpeg")]
use mv_types::motion_vector::MvCompact;

/// CLI arguments shared by every extractor binary.
///
/// Layout: `<input file> <print mv> <output file> <is verbose> <thread_count> <keyframes_only>`
///
/// `thread_count` maps directly to `AVCodecContext.thread_count`: 0 = FFmpeg
/// picks automatically, 1 = single-threaded, N = N threads.
/// `keyframes_only` = 1 enables I-frame-only decoding (stream discard + skip_frame).
pub struct ExtractorArgs {
    pub video_file: String,
    pub do_print: bool,
    pub output_file: String,
    pub is_verbose: bool,
    /// 0 = auto (FFmpeg default), 1 = single-threaded, N = N threads.
    pub thread_count: i32,
    /// Decode only I-frames; set via env var `KEYFRAMES_ONLY=1`.
    pub keyframes_only: bool,
}

impl ExtractorArgs {
    pub fn from_env() -> Option<Self> {
        let argv: Vec<String> = std::env::args().collect();
        if argv.len() < 7 {
            let exe = argv.first().cloned().unwrap_or_else(|| "extractor".to_string());
            eprintln!(
                "Usage: {} <input file> <print mv> <output file> <is verbose> <thread_count> <keyframes_only>",
                exe
            );
            return None;
        }
        let keyframes_only = argv[6] == "1";
        let mut thread_count = argv[5].parse::<i32>().unwrap_or(0);
        // Keyframes-only decodes ~2-5% of the frames with no inter-frame
        // dependencies to pipeline, so frame threads only add setup/handoff
        // cost: measured 0.024 ms/f at 1 thread vs 0.055 at 128. Clamp.
        if keyframes_only {
            thread_count = 1;
        }
        Some(Self {
            video_file: argv[1].clone(),
            do_print: argv[2].parse::<i32>().unwrap_or(0) != 0,
            output_file: argv[3].clone(),
            is_verbose: argv[4].parse::<i32>().unwrap_or(0) != 0,
            thread_count,
            keyframes_only,
        })
    }
}

/// Convenience wrapper around `MotionVectorCsvWriter<BufWriter<File>>` so
/// extractors don't have to spell out the generics.
pub type FileMvWriter = MotionVectorCsvWriter<BufWriter<File>>;

/// Compact counterpart to `FileMvWriter`, used when the decoder emits
/// `AV_FRAME_DATA_MOTION_VECTORS_COMPACT` instead of the full-size side data.
pub type FileMvCompactWriter = MvCompactCsvWriter<BufWriter<File>>;

/// Buffer for the CSV writers. The BufWriter default (8 KiB) meant a spill
/// every ~370 compact rows — VTune showed `write_all_cold` as a top-3
/// extractor hotspot. 1 MiB cuts the write syscalls ~128x.
const MV_WRITER_BUF: usize = 1 << 20;

/// Open the CSV output file and wrap it in a streaming writer.
pub fn open_mv_writer(path: &str) -> std::io::Result<FileMvWriter> {
    let file = File::create(path)?;
    MotionVectorCsvWriter::new(BufWriter::with_capacity(MV_WRITER_BUF, file))
}

pub fn open_mv_compact_writer(path: &str) -> std::io::Result<FileMvCompactWriter> {
    let file = File::create(path)?;
    MvCompactCsvWriter::new(BufWriter::with_capacity(MV_WRITER_BUF, file))
}

/// Open an `MvWriter`, picking the compact flavour when the custom FFmpeg
/// feature is enabled and the full flavour otherwise. Keeps the dispatch out
/// of every extractor binary.
pub fn open_mv_any(path: &str) -> std::io::Result<MvWriter> {
    #[cfg(feature = "custom_ffmpeg")]
    {
        Ok(MvWriter::Compact(open_mv_compact_writer(path)?))
    }
    #[cfg(not(feature = "custom_ffmpeg"))]
    {
        Ok(MvWriter::Full(open_mv_writer(path)?))
    }
}

/// Unified writer the extractors hold. Kept as an enum so the same binary can
/// deal with either side-data flavour without pulling feature gates into every
/// call site.
pub enum MvWriter {
    Full(FileMvWriter),
    Compact(FileMvCompactWriter),
}

impl MvWriter {
    pub fn total(&self) -> i64 {
        match self {
            MvWriter::Full(w) => w.total(),
            MvWriter::Compact(w) => w.total(),
        }
    }

    pub fn flush(&mut self) -> std::io::Result<()> {
        match self {
            MvWriter::Full(w) => w.flush(),
            MvWriter::Compact(w) => w.flush(),
        }
    }
}

/// Convert a raw `AVMotionVector` into our shared `MotionVector` type. Any
/// extractor writing to the CSV goes through this so the wire format stays in
/// sync with `mv_types::motion_vector::MV_COLUMNS`.
fn convert_av_mv(frame_num: i32, mv: &AVMotionVector) -> Option<MotionVector> {
    if mv.w == 0 || mv.h == 0 {
        eprintln!(
            "Invalid motion vector dimensions: {} x {}",
            mv.w as i32, mv.h as i32
        );
        return None;
    }
    Some(MotionVector {
        frame: frame_num,
        source: mv.source,
        w: mv.w as i32,
        h: mv.h as i32,
        src_x: mv.src_x as f64,
        src_y: mv.src_y as f64,
        dst_x: mv.dst_x as f64,
        dst_y: mv.dst_y as f64,
        flags: mv.flags,
        motion_x: mv.motion_x as f64,
        motion_y: mv.motion_y as f64,
        motion_scale: mv.motion_scale as f64,
    })
}

/// Append every motion vector from a frame's side-data blob to the writer.
///
/// # Safety
/// `mvs` must point to `size_bytes / size_of::<AVMotionVector>()` valid,
/// contiguous `AVMotionVector`s — exactly the pointer/size pair produced by
/// `av_frame_get_side_data` on `AV_FRAME_DATA_MOTION_VECTORS`.
pub unsafe fn write_side_data(
    writer: &mut FileMvWriter,
    frame_num: i32,
    mvs: *const AVMotionVector,
    size_bytes: usize,
) {
    if mvs.is_null() {
        eprintln!("Invalid motion vector");
        return;
    }
    let count = size_bytes / std::mem::size_of::<AVMotionVector>();
    for i in 0..count {
        let av = unsafe { &*mvs.add(i) };
        if let Some(v) = convert_av_mv(frame_num, av) {
            if let Err(e) = writer.write(&v) {
                eprintln!("Failed to write motion vector: {}", e);
                return;
            }
        }
    }
}

#[cfg(feature = "custom_ffmpeg")]
fn convert_av_mv_compact(frame_num: i32, mv: &AVMotionVectorCompact) -> MvCompact {
    MvCompact {
        frame: frame_num,
        source: mv.source,
        src_x: mv.src_x,
        src_y: mv.src_y,
        dst_x: mv.dst_x,
        dst_y: mv.dst_y,
    }
}

/// Compact counterpart to `write_side_data`. Reads a contiguous array of
/// `AVMotionVectorCompact` produced by the custom FFmpeg patch when
/// `motion_vectors_only=1` and appends each one to the compact writer.
///
/// # Safety
/// Same contract as `write_side_data` but for `AVMotionVectorCompact`.
#[cfg(feature = "custom_ffmpeg")]
pub unsafe fn write_side_data_compact(
    writer: &mut FileMvCompactWriter,
    frame_num: i32,
    mvs: *const AVMotionVectorCompact,
    size_bytes: usize,
) {
    if mvs.is_null() {
        eprintln!("Invalid motion vector");
        return;
    }
    let count = size_bytes / std::mem::size_of::<AVMotionVectorCompact>();
    for i in 0..count {
        let av = unsafe { &*mvs.add(i) };
        let v = convert_av_mv_compact(frame_num, av);
        if let Err(e) = writer.write(&v) {
            eprintln!("Failed to write motion vector: {}", e);
            return;
        }
    }
}

/// Pull motion vectors off a decoded frame and feed them to the writer,
/// picking the compact or full side-data slot based on what the decoder
/// populated. Returns `true` if any side data was found.
///
/// When built with `custom_ffmpeg`, `AV_FRAME_DATA_MOTION_VECTORS_COMPACT`
/// is checked first — the custom decoder populates exactly one of the two
/// slots based on `motion_vectors_only`.
///
/// # Safety
/// `frame` must be a valid, non-null `*mut AVFrame` owned by the caller.
pub unsafe fn write_frame_mvs(
    writer: &mut MvWriter,
    frame_num: i32,
    frame: *mut ff::AVFrame,
) -> bool {
    #[cfg(feature = "custom_ffmpeg")]
    if let MvWriter::Compact(w) = writer {
        // AV_FRAME_DATA_MOTION_VECTORS_COMPACT = 31 in the custom FFmpeg enum.
        // ffmpeg-sys-next generates AVFrameSideDataType as i32; transmute via
        // the integer repr to avoid UB on an undefined discriminant.
        let compact_type: ff::AVFrameSideDataType =
            core::mem::transmute::<i32, ff::AVFrameSideDataType>(31i32);
        let sd = ff::av_frame_get_side_data(frame, compact_type);
        if !sd.is_null() && !(*sd).data.is_null() && (*sd).size > 0 {
            write_side_data_compact(
                w,
                frame_num,
                (*sd).data as *const AVMotionVectorCompact,
                (*sd).size as usize,
            );
            return true;
        }
        // motion_vectors_only=1 not applied at runtime — convert standard
        // AVMotionVector side data to compact format (drops w/h/flags fields).
        let sd_std = ff::av_frame_get_side_data(
            frame,
            ff::AVFrameSideDataType::AV_FRAME_DATA_MOTION_VECTORS,
        );
        if !sd_std.is_null() && !(*sd_std).data.is_null() && (*sd_std).size > 0 {
            let count =
                (*sd_std).size as usize / core::mem::size_of::<ff::AVMotionVector>();
            for i in 0..count {
                let av = &*((*sd_std).data as *const ff::AVMotionVector).add(i);
                let compact = AVMotionVectorCompact {
                    source: av.source,
                    src_x: av.src_x,
                    src_y: av.src_y,
                    dst_x: av.dst_x,
                    dst_y: av.dst_y,
                };
                let v = convert_av_mv_compact(frame_num, &compact);
                if let Err(e) = w.write(&v) {
                    eprintln!("Failed to write compact MV: {}", e);
                    return false;
                }
            }
            return count > 0;
        }
        return false;
    }

    if let MvWriter::Full(w) = writer {
        let sd = ff::av_frame_get_side_data(
            frame,
            ff::AVFrameSideDataType::AV_FRAME_DATA_MOTION_VECTORS,
        );
        if !sd.is_null() && !(*sd).data.is_null() && (*sd).size > 0 {
            write_side_data(
                w,
                frame_num,
                (*sd).data as *const AVMotionVector,
                (*sd).size as usize,
            );
            return true;
        }
    }
    false
}

/// Return the current resident set size of this process in kilobytes,
/// or 0 if it cannot be read.
///
/// Linux: parses `/proc/self/status` (VmRSS). This reflects the *current*
/// RSS after `exec`, unlike `ru_maxrss` from `wait4`.
/// Windows: queries `GetProcessMemoryInfo` via psapi.
/// Other unix: returns 0 (no portable equivalent without extra deps).
#[cfg(target_os = "linux")]
pub fn get_current_rss_kb() -> i64 {
    let Ok(status) = std::fs::read_to_string("/proc/self/status") else {
        return 0;
    };
    for line in status.lines() {
        if let Some(val) = line.strip_prefix("VmRSS:") {
            let val = val.trim().trim_end_matches(" kB").trim();
            return val.parse().unwrap_or(0);
        }
    }
    0
}

#[cfg(target_os = "windows")]
pub fn get_current_rss_kb() -> i64 {
    use std::mem;
    #[repr(C)]
    struct ProcessMemoryCounters {
        cb: u32,
        page_fault_count: u32,
        peak_working_set_size: usize,
        working_set_size: usize,
        quota_peak_paged_pool_usage: usize,
        quota_paged_pool_usage: usize,
        quota_peak_non_paged_pool_usage: usize,
        quota_non_paged_pool_usage: usize,
        pagefile_usage: usize,
        peak_pagefile_usage: usize,
    }
    type Handle = *mut core::ffi::c_void;
    // K32GetProcessMemoryInfo lives in kernel32 (Vista+), so no extra .lib
    // link is needed. The legacy psapi entry point requires psapi.lib.
    #[link(name = "kernel32")]
    extern "system" {
        fn GetCurrentProcess() -> Handle;
        fn K32GetProcessMemoryInfo(
            process: Handle,
            counters: *mut ProcessMemoryCounters,
            cb: u32,
        ) -> i32;
    }
    unsafe {
        let mut pmc: ProcessMemoryCounters = mem::zeroed();
        pmc.cb = mem::size_of::<ProcessMemoryCounters>() as u32;
        if K32GetProcessMemoryInfo(GetCurrentProcess(), &mut pmc, pmc.cb) != 0 {
            (pmc.working_set_size / 1024) as i64
        } else {
            0
        }
    }
}

/// Print the FFmpeg runtime version to stderr.
pub fn print_ffmpeg_version() {
    unsafe {
        let v = CStr::from_ptr(ff::av_version_info()).to_string_lossy();
        eprintln!("FFmpeg version: {}", v);
    }
}

/// Apply the custom fork's motion-vector post-filter AVOptions, read from the
/// environment (the makefile exports both via BENCH_ENV).
///
/// * `MV_GRID=N`      — export at most one vector per N x N pixel cell.
/// * `MV_SKIP_EVERY_NTH=N` — skip every Nth picture outright (saves decode time).
/// * `MV_MIN_SIZE=N`  — drop vectors whose displacement is shorter than N pixels.
///
/// Unset, `0` or unparseable means "no filter", and in that case nothing is set
/// at all, so default runs stay byte-identical to before these options existed.
/// Both options exist only in the custom FFmpeg; against the regular build
/// `av_opt_set_int` just returns AVERROR_OPTION_NOT_FOUND, which is why the
/// extractors can call this unconditionally (same as `mv_l0_only` already does).
pub unsafe fn set_mv_filter_opts(dec_ctx: *mut ff::AVCodecContext) {
    for (opt, env) in [
        ("mv_grid", "MV_GRID"),
        ("mv_min_size", "MV_MIN_SIZE"),
        // Temporal decimation: unlike the two above, this one actually cuts
        // decode time, because a skipped picture never reaches the entropy
        // decoder. See mv_skip_every_nth in the fork's avcodec.h.
        ("mv_skip_every_nth", "MV_SKIP_EVERY_NTH"),
    ] {
        let value = std::env::var(env)
            .ok()
            .and_then(|v| v.trim().parse::<i64>().ok())
            .unwrap_or(0);
        if value > 0 {
            let key = CString::new(opt).unwrap();
            ff::av_opt_set_int(dec_ctx as *mut std::ffi::c_void, key.as_ptr(), value, 0);
        }
    }
}

/// CSV frame numbering that follows the SOURCE picture sequence rather than
/// counting what came out of the decoder.
///
/// The two are the same until pictures start being dropped. `MV_SKIP_EVERY_NTH=5`
/// makes the decoder emit nothing for every fifth picture, and a plain output
/// counter then closes the gap - source picture 6 is written as frame 5 - so the
/// CSV claims motion at times the run never looked at, every row after the first
/// drop is attributed to the wrong picture, and nothing lines up with the same
/// clip decoded undecimated. Numbering by source position instead leaves a
/// skipped picture's index simply absent, which is what a reader can act on:
/// "frame 5 is missing" is the truth, "frame 5 is what used to be frame 6" is
/// not.
///
/// The index comes from the frame's PTS, not from the decoder, because the drop
/// happens in three different places - `skip_frame` in the shared slice header
/// path, `mv_skip_every_nth` in the fork's h264/hevc slice code, and the
/// demuxer's own `discard` - and a timestamp is what all three preserve. Frames
/// are emitted in display order, so PTS rises monotonically and
/// `elapsed_ticks / ticks_per_picture` is exact on constant-frame-rate input.
///
/// Deliberately inert unless decimation is actually configured. With nothing
/// being dropped the output counter already IS the source position, so falling
/// back to it keeps every existing run - and every CSV ever compared against one
/// - byte-identical, and sidesteps variable-frame-rate clips where the PTS
/// arithmetic would not hold. Same reasoning as `set_mv_filter_opts`: a default
/// run must look exactly as it did before the feature existed.
pub struct SourceFrameIndex {
    /// PTS units per source picture. 0 means "just count", either because no
    /// decimation is configured or because the stream lacks a usable rate.
    ticks: i64,
    /// PTS that maps to index 0. `i64::MIN` until the first frame sets it.
    origin: i64,
    /// Frames actually decoded - what the benchmark's ms/frame is divided by,
    /// and what the extractor prints as its frame count. NOT a source position.
    decoded: i32,
}

/// True when any picture-dropping knob is set, i.e. when output order can
/// diverge from source order. Reads the same environment the option setters do.
fn decimation_configured() -> bool {
    let nth = std::env::var("MV_SKIP_EVERY_NTH")
        .ok()
        .and_then(|v| v.trim().parse::<i64>().ok())
        .unwrap_or(0);
    if nth > 1 {
        return true;
    }
    match std::env::var("MV_SKIP_FRAME") {
        Ok(mode) => {
            let mode = mode.trim();
            !mode.is_empty() && mode != "none"
        }
        Err(_) => false,
    }
}

impl SourceFrameIndex {
    /// # Safety
    /// `video_stream` must be a valid `*const AVStream` from the open format
    /// context, live for the call.
    pub unsafe fn new(video_stream: *const ff::AVStream) -> Self {
        let mut me = SourceFrameIndex { ticks: 0, origin: i64::MIN, decoded: 0 };
        if !decimation_configured() {
            return me;
        }

        let tb = (*video_stream).time_base;
        // avg_frame_rate is the container's own answer; r_frame_rate is
        // libavformat's guess from the timestamps, and is the better fallback
        // than giving up.
        let mut fr = (*video_stream).avg_frame_rate;
        if fr.num <= 0 || fr.den <= 0 {
            fr = (*video_stream).r_frame_rate;
        }
        if fr.num <= 0 || fr.den <= 0 || tb.num <= 0 || tb.den <= 0 {
            eprintln!(
                "MV_SKIP_*: stream has no usable frame rate / time base - CSV frame \
                 numbers will stay sequential and will not show the skipped pictures"
            );
            return me;
        }

        // One picture period (1/fr) expressed in time_base units. av_inv_q is a
        // static inline, so it is not in the bindings - invert by hand.
        let period = ff::AVRational { num: fr.den, den: fr.num };
        let ticks = ff::av_rescale_q(1, period, tb);
        if ticks <= 0 {
            eprintln!(
                "MV_SKIP_*: frame period rounds to {} time_base units - CSV frame \
                 numbers will stay sequential",
                ticks
            );
            return me;
        }
        me.ticks = ticks;

        // The container's first presentation timestamp is index 0. When it is
        // unknown the first decoded frame supplies the origin instead, which is
        // the same picture in practice: every skip mode exempts IDR, so the
        // first picture out is the first picture in.
        let start = (*video_stream).start_time;
        if start != i64::MIN {
            me.origin = start;
        }
        me
    }

    /// Source position of `frame`, and one more frame counted as decoded.
    /// Call exactly once per received frame, before `av_frame_unref`.
    ///
    /// # Safety
    /// `frame` must be a valid, non-null `*const AVFrame` still holding the
    /// decoder's output.
    pub unsafe fn index_of(&mut self, frame: *const ff::AVFrame) -> i32 {
        let sequential = self.decoded;
        self.decoded += 1;

        if self.ticks == 0 {
            return sequential;
        }

        // AV_NOPTS_VALUE is a C macro (INT64_MIN), so bindgen emits no constant.
        let mut pts = (*frame).pts;
        if pts == i64::MIN {
            pts = (*frame).best_effort_timestamp;
        }
        if pts == i64::MIN {
            return sequential;
        }
        if self.origin == i64::MIN {
            self.origin = pts;
        }

        let delta = pts - self.origin;
        if delta < 0 {
            return sequential;
        }
        ((delta + self.ticks / 2) / self.ticks) as i32
    }

    /// How many frames were decoded. This is the frame COUNT the benchmark
    /// divides wall time by - not the last index written, which is larger
    /// whenever pictures were skipped.
    pub fn decoded(&self) -> i32 {
        self.decoded
    }
}

/// Temporal decimation: drop whole pictures before they are entropy-decoded.
///
/// `MV_SKIP_FRAME` accepts FFmpeg's `skip_frame` vocabulary — `noref`, `bidir`,
/// `nointra`, `nokey` — and is unset by default. Unlike the spatial filters in
/// `set_mv_filter_opts`, this one genuinely saves decode time: a discarded
/// picture has none of its CABAC bins consumed at all.
///
/// Safe for the pictures that are still decoded, because H.264 predicts motion
/// vectors from *spatial* neighbours within the same slice. The only cross-
/// picture MV dependency is a B slice's temporal direct mode, which needs the
/// collocated MV field — so dropping all B pictures (`bidir`) leaves the
/// surviving I/P motion vectors bit-exact, while dropping references would not.
pub unsafe fn set_skip_frame_opt(dec_ctx: *mut ff::AVCodecContext) {
    let Ok(mode) = std::env::var("MV_SKIP_FRAME") else { return };
    let mode = mode.trim();
    if mode.is_empty() || mode == "none" {
        return;
    }
    // Set by option NAME, not by struct field: the custom fork inserts fields
    // into AVCodecContext, so every offset after codec_id differs from what
    // ffmpeg-sys-next's bindings expect and a direct `(*dec_ctx).skip_frame =`
    // lands on the wrong field. Same reason extractor1.rs uses the dict API for
    // flags2. av_opt_set resolves "skip_frame" through the DLL's own offsetof.
    let key = CString::new("skip_frame").unwrap();
    let val = CString::new(mode).unwrap();
    let rc = ff::av_opt_set(dec_ctx as *mut std::ffi::c_void, key.as_ptr(), val.as_ptr(), 0);
    if rc < 0 {
        eprintln!("MV_SKIP_FRAME: could not set skip_frame={:?} (rc={})", mode, rc);
    }
}

pub unsafe fn set_av_flags(fmt_ctx: &mut ff::AVFormatContext) -> Vec<*mut ff::AVDictionary> {
    let nb_streams = (*fmt_ctx).nb_streams as usize;
    let mut stream_opts: Vec<*mut ff::AVDictionary> = vec![ptr::null_mut(); nb_streams];

    let mv_only_key = CString::new("motion_vectors_only").unwrap();
    let mv_only_val = CString::new("1").unwrap();
    let export_key = CString::new("export_side_data").unwrap();
    let export_val = CString::new("+mvs").unwrap();

    for i in 0..nb_streams {
        ff::av_dict_set(&mut stream_opts[i], mv_only_key.as_ptr(), mv_only_val.as_ptr(), 0);
        ff::av_dict_set(&mut stream_opts[i], export_key.as_ptr(), export_val.as_ptr(), 0);
    }

    stream_opts
}

pub unsafe fn unset_av_flags(stream_opts: Vec<*mut ff::AVDictionary>) { 
    for mut dict in stream_opts {
        if !dict.is_null() {
            ff::av_dict_free(&mut dict);
        }
    }
}